# Generated by Django 4.1.1 on 2022-10-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Est_civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parentescos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FilePathField(max_length=50, path='/static/personal/img')),
                ('legajo', models.SmallIntegerField()),
                ('apellidos', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=40)),
                ('id_documento', models.SmallIntegerField()),
                ('documento', models.IntegerField()),
                ('cuil', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('id_categoria', models.SmallIntegerField()),
                ('id_est_civil', models.SmallIntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('id_localidad', models.IntegerField()),
                ('id_provincia', models.SmallIntegerField()),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('saldo_licencia', models.SmallIntegerField()),
                ('licencia_curso', models.SmallIntegerField()),
                ('fecha_regreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cp_localidad', models.IntegerField()),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.provincias')),
            ],
        ),
    ]
