# Generated by Django 4.1.1 on 2022-10-29 20:43

from django.db import migrations
import personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=personal.models.NameField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombres',
            field=personal.models.NameField(max_length=40, verbose_name='Nombres'),
        ),
    ]
