# Generated by Django 4.1.1 on 2022-10-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cuil',
            field=models.BigIntegerField(),
        ),
    ]
