# Generated by Django 4.1.1 on 2022-10-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_egreso',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_regreso',
            field=models.DateField(blank=True),
        ),
    ]
