# Generated by Django 4.1.3 on 2023-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_apellidos_alter_personal_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='licencia_curso',
            field=models.SmallIntegerField(default=2023, verbose_name='Licencia en Curso'),
        ),
    ]
