# Generated by Django 4.1.1 on 2022-10-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_personal_fecha_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
