# Generated by Django 4.1.1 on 2022-10-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.tipo_doc'),
        ),
    ]
