# Generated by Django 4.1.1 on 2022-10-09 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_personal_id_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.categorias'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_est_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.est_civil'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.localidades'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.provincias'),
        ),
    ]
