# Generated by Django 4.1.1 on 2022-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_personal_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='fotos_pers'),
        ),
    ]
