# Generated by Django 4.1.1 on 2022-10-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_personal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cuil',
            field=models.BigIntegerField(verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.IntegerField(verbose_name='Num. Documento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='domicilio',
            field=models.CharField(max_length=50, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Regreso'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='fotos_pers', verbose_name='Foto Personal'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.categorias', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.tipo_doc', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_est_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.est_civil', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.localidades', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.provincias', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='legajo',
            field=models.SmallIntegerField(verbose_name='Lejajo Num.'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='licencia_curso',
            field=models.SmallIntegerField(verbose_name='Licencia en Curso'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombres',
            field=models.CharField(max_length=40, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='saldo_licencia',
            field=models.SmallIntegerField(verbose_name='Saldo de Licencia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tel',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
