# Generated by Django 4.1.1 on 2022-10-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_personal_licencia_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'personal', 'verbose_name_plural': 'Personal'},
        ),
    ]
