# Generated by Django 4.1.1 on 2022-10-22 00:50

from django.db import migrations, models
import personal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_alter_personal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cuil',
            field=models.BigIntegerField(max_length=11, verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.IntegerField(max_length=8, verbose_name='Num. Documento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(validators=[personal.validators.validate_fecha_nacimiento], verbose_name='Fecha de Nacimiento'),
        ),
    ]
