# Generated by Django 4.1.1 on 2022-10-22 20:20

from django.db import migrations, models
import personal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_personal_cuil_alter_personal_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cuil',
            field=models.CharField(max_length=11, validators=[personal.validators.validate_cuil], verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.CharField(max_length=8, validators=[personal.validators.validate_dni], verbose_name='Num. Documento'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_ingreso',
            field=models.DateField(validators=[personal.validators.validate_fecha_ingreso], verbose_name='Fecha de Ingreso'),
        ),
    ]
