# Generated by Django 4.1.3 on 2023-02-16 21:21

from django.db import migrations, models
import django.db.models.deletion
import licencias.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0004_eventos_prt_planilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(validators=[licencias.validators.validate_fecha_desde], verbose_name='Fecha de Inicio')),
                ('fecha_hasta', models.DateField(validators=[licencias.validators.validate_fecha_hasta], verbose_name='Fecha de Fin')),
                ('cantidad', models.SmallIntegerField()),
                ('borrable', models.BooleanField()),
                ('afecta_vac', models.BooleanField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.eventos', verbose_name='Tipo de Evento')),
            ],
        ),
    ]
