# Generated by Django 4.1.1 on 2022-10-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajos',
            name='id_empleado',
        ),
        migrations.AddField(
            model_name='legajos',
            name='id_empleado',
            field=models.ManyToManyField(to='personal.personal'),
        ),
    ]
