# Generated by Django 4.1.1 on 2022-10-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_remove_legajos_id_empleado_legajos_id_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajos',
            name='id_evento',
        ),
        migrations.AddField(
            model_name='legajos',
            name='id_evento',
            field=models.ManyToManyField(to='personal.eventos'),
        ),
    ]
