# Generated by Django 4.1.3 on 2023-01-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0003_remove_legajos_id_evento_legajos_id_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Legajos',
        ),
    ]
