# Generated by Django 4.1.3 on 2023-01-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_licencia_curso'),
        ('licencias', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.eventos'),
        ),
    ]
