# Generated by Django 4.1.3 on 2023-01-24 22:58

from django.db import migrations, models
import django.db.models.deletion
import licencias.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_licencia_curso'),
        ('licencias', '0006_alter_legajos_id_empleado_alter_legajos_id_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='fecha_desde',
            field=models.DateField(validators=[licencias.validators.validate_fecha_desde], verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fecha_hasta',
            field=models.DateField(validators=[licencias.validators.validate_fecha_hasta], verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.eventos', verbose_name='Tipo de Evento'),
        ),
    ]
